name: Build SDMAC

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: liv2/amiga-gcc-amitools
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Invoke Makefile
        run: make all