name: Build SDMAC

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/mbtaylor1982/container-amiga-gcc-amitools:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Invoke Makefile
        run: make all lha adf zip
